name: Build Windows Installer

on:
  push:
    branches: [ main ] # سيشتغل البناء تلقائياً عند الرفع على فرع main

jobs:
  build:
    runs-on: windows-latest # هنا نطلب من جيت هاب توفير سيرفر ويندوز

    steps:
    - name: Enable Long Paths
      run: git config --system core.longpaths true
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Install dependencies
      run: flutter pub get

    - name: Enable Windows support
      run: flutter config --enable-windows-desktop

    - name: Build Windows (Release)
      run: flutter build windows --release

    - name: Create EXE Installer (Inno Setup)
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" innosetup.iss
      shell: powershell

    - name: Upload EXE Installer
      uses: actions/upload-artifact@v4
      with:
        name: Al-Sakr-EXE-Installer
        path: build/windows/installer/*.exe
